---
- name: Deploying Artifact
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Test
    shell: ls
  - name: Copy file
    copy:
      src: /opt/jenkins/workspace/java-pipeline/target/springboot-bootcamp-0.0.1-SNAPSHOT.jar"
      dest: /home/ubuntu
      remote_src: yes

  - name: Running Artifact
    shell: java -jar /home/ubuntu/springboot-bootcamp-0.0.1-SNAPSHOT.jar

